[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = "dist"

# Redirect for art-appraisers-landing
[[redirects]]
  from = "/art-landing/*"
  to = "/art-appraisers-landing/:splat"
  status = 200

# SPA fallback for main_page
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 