[build]
  command = "npm run build"
  publish = "dist"
  
[build.environment]
  NODE_VERSION = "20"

# Redirect for the art appraiser directory
[[redirects]]
  from = "/directory/*"
  to = "/directory/:splat"
  status = 200

# Redirect for the art appraisers landing pages
[[redirects]]
  from = "/art-appraiser/*"
  to = "/landing/art-appraiser/:splat"
  status = 200

[[redirects]]
  from = "/painting-value/*"
  to = "/landing/painting-value/:splat"
  status = 200

# Redirect for the art appraisal screener pages
[[redirects]]
  from = "/screener/*"
  to = "/screener/:splat"
  status = 200

# Art appraiser specific paths
[[redirects]]
  from = "/location/*"
  to = "/directory/location/:splat"
  status = 200

[[redirects]]
  from = "/appraiser/*"
  to = "/directory/appraiser/:splat"
  status = 200

# Sitemap configuration
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Content-Type = "application/xml"
    X-Robots-Tag = "noarchive"

# Handle client-side routing for main application
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security Headers based on main_page settings
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = """
      default-src 'self' https: data: blob:;
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://*.tawk.to https://embed.tawk.to https://cdn.jsdelivr.net https://unpkg.com https://*.appraisily.com https://www.googleadservices.com https://www.google-analytics.com https://googleads.g.doubleclick.net https://*.netlify.app;
      style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://*.tawk.to https://*.appraisily.com https://*.netlify.app;
      img-src 'self' data: https: blob:;
      font-src 'self' data: https://fonts.gstatic.com https://*.tawk.to;
      connect-src 'self' https: wss://*.tawk.to wss://*.us-central1.run.app https://www.google-analytics.com https://stats.g.doubleclick.net;
      frame-src 'self' https://*.tawk.to https://www.youtube.com https://www.googletagmanager.com https://*.appraisily.com;
      worker-src 'self' blob:;
      child-src blob:;
      media-src 'self' https:;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
      upgrade-insecure-requests;
    """

# Cache static assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 