# Netlify configuration for the Appraisily monorepo

[build]
  command = "npm run build"
  publish = "dist"
  ignore = "git diff --quiet HEAD^ HEAD -- ./main_page ./art-appraisers-landing"

[build.environment]
  NODE_VERSION = "18"
  SECRETS_SCAN_ENABLED = "false"
  NPM_FLAGS = "--no-audit --no-fund"
  
# Create a dist directory by copying all submodule dist folders
[build.processing]
  skip_processing = false

# Main Page Routes - Keep at root
[[redirects]]
  from = "/"
  to = "/main_page/dist/index.html"
  status = 200

# Art Appraisers Landing Routes
[[redirects]]
  from = "/art-appraisers/*"
  to = "/art-appraisers-landing/dist/index.html"
  status = 200

[[redirects]]
  from = "/painting-value/*"
  to = "/art-appraisers-landing/dist/painting-value/index.html"
  status = 200

# Assets and static files from main page
[[redirects]]
  from = "/assets/*"
  to = "/main_page/dist/assets/:splat"
  status = 200

# Assets from landing page
[[redirects]]
  from = "/art-appraisers/assets/*"
  to = "/art-appraisers-landing/dist/assets/:splat"
  status = 200

# Handle fallback for client-side routing
[[redirects]]
  from = "/*"
  to = "/main_page/dist/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net https://www.googletagmanager.com; connect-src 'self' https://*.supabase.co https://api.appraisily.com; img-src 'self' data: https://images.appraisily.com https://*.supabase.co; style-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; font-src 'self' data:; frame-src 'self'; object-src 'none'"

# Cache static assets
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 